services:
  - type: web
    name: fekracode-laravel
    env: docker
    plan: free
    region: singapore
    dockerfilePath: /Dockerfile
    repo: https://github.com/amarmansor01/fekracode-laravel
    branch: main
    buildFilter:
      paths:
        - demo-app/**
