services:
  - type: web
    name: fekracode-laravel
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    repo: https://github.com/amarmansor01/fekracode-laravel
    branch: main
    numInstances: 1
